name: Deploy Example Site

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  site:
    uses: ./.github/workflows/kicad-site.yml
    with:
      project_name: "Arduino_Uno"
      schematic: "Arduino_Uno.kicad_sch"
      pcb: "Arduino_Uno.kicad_pcb"
      kicad_dir: "example"
      site_dir: "exampleSite"
      site_base_url: "https://laenzlinger.github.io/hugo-kicad-site"
