name: Hextra Preview

on:
  push:
    branches: [feature/hextra-theme]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/kicad-site.yml
    with:
      project_name: "Arduino_Uno"
      schematic: "Arduino_Uno.kicad_sch"
      pcb: "Arduino_Uno.kicad_pcb"
      kicad_dir: "example"
      kibot_config: "Arduino_Uno.kibot.yaml"
      site_dir: "exampleSite"
      site_base_url: "https://laenzlinger.github.io/hugo-kicad-site/hextra-preview"
      assembly_dir: "example"
      remove_step_file: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          name: site-latest
          path: site

      - name: Deploy to hextra-preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          target-folder: hextra-preview/latest
          clean: false
